
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from './page.module.css';
import "../(site)/globals.css";
import { Footer, Header } from '../../components';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SignIn/Register",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
  session: any;
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div className={styles.wrapper}>
          <Header className={styles.header} />
          <div className={styles.body}>
            {children}
          </div>
          <Footer className={styles.footer} />
        </div>

      </body>
    </html>
  );
}

