
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from '../../components';
import styles from "../(site)/page.module.css";
import "../(site)/globals.css";
import { HeaderForAdmin } from '../../components/HeaderForAdmin/HeaderForAdmin';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Doctor's side",
  description: "Generated by create next app",
};


export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div className={styles.wrapper}>
          <HeaderForAdmin className={styles.header} />
          <div className={styles.body}>
            {children}
          </div>
          <Footer className={styles.footer} />
        </div>

      </body>
    </html>
  );
}